# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0001_initial'),
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='student',
            name='c',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='c_plus_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='c_sharp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='django',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='java',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='javascript',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='perl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='php',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='sql',
            field=models.BooleanField(default=False),
        ),
    ]
