# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('companyForProject', models.TextField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('specialty', models.TextField(blank=True, max_length=10000, null=True)),
                ('years', models.CharField(blank=True, max_length=10, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
